name: ci-dev

on:
  push:
    branches:
      - "dev"

jobs:
  db:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: ./Dockerfiledb ./db.sql

      - name: Deploy Files to Server
        uses: appleboy/scp-action@master
        # env:
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "Dockerfiledb,db.sql"
          taget: "app_file"
